apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: frontend-ingressclass
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
spec:
  controller: k8s.io/ingress-nginx