backend:
  image:
    name: geonhyukseo/goormback
    tag: e80ca388ef0022cc3dfd8c8b86dee1e463f1306f
  environments:
    DATABASE_URL: postgresql://root:root@localhost:30032/goormbread?schema=public
    REDIS_SESSION_URL: redis://localhost:30079/0
    REDIS_LOBBY_URL: redis://localhost:30079/1
    SESSION_SECRET_KEY: jglskjglskdgjdlkfbjdofjwvefkvcqwp
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 4f3175eec562de7c7ef27172b472961b7cd61963
