backend:
  image:
    name: geonhyukseo/goormback
    tag: cdaa48f9d6fd156e8f250f5bcd5a4726c36d0019
  env:
    DATABASE_URL: "postgresql://root:root@localhost:30032/goormbread?schema: public"
    REDIS_SESSION_URL: "redis://localhost:30079/0"
    REDIS_LOBBY_URL: "redis://localhost:30079/1"
    SESSION_SECRET_KEY: "jglskjglskdgjdlkfbjdofjwvefkvcqwp"
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 4e21d635c76d5feb8afebee069a1180be24e7763
