backend:
  image:
    name: geonhyukseo/goormback
    tag: f42f60b3f9393dcabe93ccc248a61b91a2ab6a16
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 4e21d635c76d5feb8afebee069a1180be24e7763
