backend:
  image:
    name: geonhyukseo/goormback
    tag: 3238c0015f5dcd0070895631f25cbda7e108f499
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 4e21d635c76d5feb8afebee069a1180be24e7763
