backend:
  image:
    name: geonhyukseo/goormback
    tag: 47688a991894c83e63075e78782638dd0cb6c5bc
environments:
  DATABASE_URL: postgresql://root:root@localhost:30032/goormbread?schema=public
  REDIS_URL: redis://localhost:30079
  SESSION_SECRET_KEY: jglskjglskdgjdlkfbjdofjwvefkvcqwp
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 409eecdbb0cea979d779a3bd18f8c65ede9f7405
