backend:
  image:
    name: geonhyukseo/goormback
    tag: 16e88575cc3f4390b089f1441711738eb024a1ad
environments:
  DATABASE_URL: postgresql://root:root@localhost:30032/goormbread?schema=public
  REDIS_URL: redis://localhost:30079
  SESSION_SECRET_KEY: jglskjglskdgjdlkfbjdofjwvefkvcqwp
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 5bca3fc25d3bf00a03eadbf7e23eb18caa7f5a2d
