backend:
  image:
    name: geonhyukseo/goormback
    tag: fb1541f72953deba3cceec365f428ca467a4e935
  environments:
    DATABASE_URL: postgresql://root:root@localhost:30032/goormbread?schema=public
    REDIS_SESSION_URL: redis://localhost:30079/0
    REDIS_LOBBY_URL: redis://localhost:30079/1
    SESSION_SECRET_KEY: jglskjglskdgjdlkfbjdofjwvefkvcqwp
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 1fb3e488fd5074ccbd75f0317555acb6dcd94f23
