backend:
  image:
    name: geonhyukseo/goormback
    tag: c367f35f46f9a0f4ddfaff5f9d7fa41a18e6cc09
environments:
  DATABASE_URL: postgresql://root:root@localhost:30032/goormbread?schema=public
  REDIS_URL: redis://localhost:30079
  SESSION_SECRET_KEY: jglskjglskdgjdlkfbjdofjwvefkvcqwp
frontend:
  image:
    name: geonhyukseo/goormfront
    tag: 409eecdbb0cea979d779a3bd18f8c65ede9f7405
